apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        volumeMounts:
        - name: persistent-storage
          mountPath: /data-db
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim

