apiVersion: v1
kind: Pod
metadata:
  name: dep-jenkins
  labels:
    app: jenkins
spec:
  containers:
    - name: jenkinsone
      image: jenkins/jenkins:lts
      volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
  volumes:
    - name: jenkins-home
      hostPath:
        path: /root/jenkins_data
        type: Directory
