apiVersion: v1
kind: Pod
metadata:
  name: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: jenkins-data
      mountPath: /var/jenkins_home
  volumes:
  - name: jenkins-data
    persistentVolumeClaim:
      claimName: jenkins-pvc

