apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset12
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:lts
        ports:
          - containerPort: 8080
          - containerPort: 50000
